apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-eureka-service
  namespace: ase-ns-03
spec:
  selector:
    matchLabels:
      app: cc-eureka-service
  replicas: 1
  template:
    metadata:
      labels:
        app: cc-eureka-service
    spec:
      containers:
      - name: cc-eureka-service
        image: httdty2/cc-eureka-service
        imagePullPolicy: Always
        ports:
        - containerPort: 9091
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 200m
            memory: 500Mi
        readinessProbe:
          tcpSocket:
            port: 9091
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 5

---

apiVersion: v1
kind: Service
metadata:
  name: cc-eureka-service
  namespace: ase-ns-03
spec:
  ports:
    - name: http
      port: 9091
  selector:
   app: cc-eureka-service
  type: LoadBalancer

