
apiVersion: v1
kind: Service
metadata:
  name: cc-ui-service
  namespace: ase-ns-03
spec:
  ports:
    - port: 80
      protocol: TCP
  selector:
    app: ui
  type: LoadBalancer


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui-deploy
  namespace: ase-ns-03
  labels:
    app: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: ui
          image:  httdty2/cc-ui-service
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi