apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-ui-service
  namespace: ase-ns-03
spec:
  selector:
    matchLabels:
      app: cc-ui-service
  replicas: 1
  template:
    metadata:
      labels:
        app: cc-ui-service
    spec:
      containers:
      - name: cc-ui-service
        image: httdty2/cc-ui-service
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 100m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi

---

apiVersion: v1
kind: Service
metadata:
  name: cc-ui-service
  namespace: ase-ns-03
spec:
  type: NodePort
  ports:
    - name: http
      port: 8080
      nodePort: 30000
  selector:
   app: cc-ui-service