apiVersion: v1
kind: Service
metadata:
  name: cc-ui-service
  namespace: ase-ns-03
spec:
  ports:
    - port: 8080
      protocol: TCP
  selector:
    app: cc-ui-service
  type: LoadBalancer

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: cc-ui-service
  namespace: ase-ns-03
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cc-ui-service
  template:
    metadata:
      labels:
        app: cc-ui-service
    spec:
      containers:
        - name: cc-ui-service
          image: httdty2/cc-ui-service
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          resources:
            requests:
              cpu: 100m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi